import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section>
      <div className="">
        <div className="">
          <div className="">
            <h1>Your details</h1>
            <p>If you already have an account, click here to log in.</p>
          </div>
          <div className="">
            <form action="">
              <label htmlFor="">First Name</label>
              <input type="text" name="" id="" />
              <label htmlFor="">Last Name</label>
              <input type="text" name="" id="" />
              <label htmlFor="">Address</label>
              <input type="text" name="" id="" />
              <label htmlFor="">City</label>
              <input type="text" name="" id="" />
              <label htmlFor="">Country</label>
              <input type="text" name="" id="" />
              <span> <input type="checkbox" name="" id="" />
              <p>Ship to the billing address</p></span>
              <button>Place order</button>
            </form>
          </div>
        </div>
        <div className="">
          <h1>Your cart</h1>
          <p>If price</p>
        </div>
      </div>
    </section>
    </div>
  )
}

export default Home
