import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="flex flex-wrap gap-8 w-full md:w-[80%] mx-auto md:mt-24">
          <div className="space-y-6 py-8 px-8 lg:w-[48%] md:w-full">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold">Your details</h1>
              <p>If you already have an account, click here to log in.</p>
            </div>
            <div className="w-[418px] ">
              <form
                action=""
                className="flex gap-3 justify-start items-start flex-col"
              >
                <div className="gap-y-4 gap-2 flex items-center flex-wrap justify-center">
                <span className="flex flex-col">
                  <label className="px-2 pb-2">First Name</label>
                  <input
                    className="bg-[#edf2f7] outline-none rounded py-1 px-3"
                    placeholder="Hamza"
                    type="text"
                    name=""
                    id=""
                  />
                </span>
                <span className="flex flex-col">
                  <label className="px-2 pb-2">Last Name</label>
                  <input
                    className="bg-[#edf2f7] outline-none rounded py-1 px-3"
                    placeholder="Ali"
                    type="text"
                    name=""
                    id=""
                  />
                </span>
                <span className="flex flex-col w-full">
                  <label className="px-2 pb-2">Address</label>
                  <input
                    className="bg-[#edf2f7] outline-none rounded py-1 px-3"
                    placeholder="House No l 460 Sector 11/E North Karachi"
                    type="text"
                    name=""
                    id=""
                  />
                </span>
                <span className="flex flex-col">
                  <label className="px-2 pb-2">City</label>
                  <input
                    className="bg-[#edf2f7] outline-none rounded py-1 px-3"
                    placeholder="Karachi"
                    type="text"
                    name=""
                    id=""
                  />
                </span>
                <span className="flex flex-col">
                  <label className="px-2 pb-2">Country</label>
                  <input
                    className="bg-[#edf2f7] outline-none rounded py-1 px-3"
                    placeholder="Pakistan"
                    type="text"
                    name=""
                    id=""
                  />
                </span>
                </div>
                <div className="flex gap-2">
                  <input type="checkbox" className="" name="" id="" />
                  <p>Ship to the billing address</p>
                </div>
                <button className="px-14 py-2 w-full bg-[#8ac919] text-white">
                  Place order
                </button>
              </form>
            </div>
          </div>
          <div className="bg-[#f7fafc] w-full py-8 px-8 lg:w-[48%] md:w-full">
            <div className="space-y-2">
              <h1 className="font-bold text-4xl">Your cart</h1>
              <p>
                If price is too hard your eyes, <b>try changing the theme.</b>
              </p>
            </div>
            <div className="mt-4 flex flex-w justify-between items-center">
              <span className="flex flex-wrap items-center">
                <img
                  className="md:w-32 w-20"
                  src="https://www.freeiconspng.com/thumbs/fast-food-png/fast-food-png-most-popular-fast-food-snacks-in-your-area-and-most--3.png"
                  alt=""
                />
                <span>
                  <h3 className="text-sm font-bold">Penny board</h3>
                  <p className="text-sm text-gray-500">PNYCOMP27541</p>
                </span>
              </span>
              <span className="font-bold">$119.00</span>
            </div>
            <div className="space-y-2">
              <span className="flex justify-between">
                <h1  className="text-gray-500">Subtotal</h1>
                <h2 className="font-bold">$19.99</h2>
              </span>
              <span className="flex justify-between">
                <h1  className="text-gray-500">Subtotal</h1>
                <h2 className="font-bold">$23.80</h2>
              </span>
              <span className="flex justify-between">
                <h1  className="text-gray-500">Subtotal</h1>
                <h2 className="font-bold">$118.00</h2>
              </span>
              <hr />
              <span className="pt-2 flex justify-between">
                <h5  className="text-gray-500">Total</h5>
                <h1 className="font-bold text-2xl">$162.79</h1>
              </span>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
